# Hardware simulator checks

all: bit register ram8 ram64 pc

bit:
	n2ths Bit.tst

register:
	n2ths Register.tst

ram8:
	n2ths RAM8.tst

ram64:
	n2ths RAM64.tst

pc:
	n2ths PC.tst

clean:
	rm -f Bit.out  PC.out  RAM64.out  RAM8.out  Register.out
